  import * as jssip from 'jssip'
  import { RefObject } from 'react';

  export interface JssipState {
      ua                                   : jssip.UA,
      sessions                             : {currentSession: jssip.RTCSession | null},
      phoneNumber                          : String,
      server                               : String,
      jssipconfiguration                   : jssip.UserAgentConfiguration,
      isRegistered                         : boolean,
      remoteVideoRef                       : RefObject<HTMLVideoElement>,
      selfVideoRef                         : RefObject<HTMLVideoElement>,
      //storedSelfStream                     : MediaStream | undefined,
      //storedRemoteStream                   : MediaStream | undefined,
      uaSipEventCallbackStack              : Array<Function>,
      uaConnectedCallbackStack             : Array<Function>,
      uaConnectingCallbackStack            : Array<Function>,
      uaDisconnectedCallbackStack          : Array<Function>,
      uaRegisteredCallbackStack            : Array<Function>,
      uaRegistrationFailedCallbackStack    : Array<Function>,
      uaRegistrationTimeoutCallbackStack   : Array<Function>,
      uaUngresiteredCallbackStack          : Array<Function>,
      uaNewRTCSessionCallbackStack         : Array<Function>,
      sessionAcceptedCallbackStack         : Array<Function>,
      sessionEndedCallbackStack            : Array<Function>,
      sessionFailedCallbackStack           : Array<Function>,
      sessionConfirmedCallbackStack        : Array<Function>,
      sessionConnectingCallbackStack       : Array<Function>,
      peerCreateOfferFailCallbackStack     : Array<Function>,
      peerCreateAnswerFailCallbackStack    : Array<Function>,
      peerSetLocalDescFailCallbackStack    : Array<Function>,
      peerSetRemoteDesFailCallbackStack    : Array<Function>,
      getUserMediaFailedCallBackStack      : Array<Function>,
      currentSessionConnectionCallbackStack: Array<Function>,
  }